import { WadaColor, wadaColorsByRomaji } from './wadaColor';

export class WadaPalette extends Array<WadaColor> {
	constructor(...colors: WadaColor[]) {
		super(...colors);
	}
}

const WP = WadaPalette;
const r = wadaColorsByRomaji;
export const wadaPalettesByNum: [number, WadaPalette][] = [
	[1, new WP(r.kabairo, r.hanaasagi)],
	[2, new WP(r.kokihanada, r.koujiiro)],
	[3, new WP(r.usutamagoiro, r.hiwadairo)],
	[4, new WP(r.ayameiro, r.ochibairo)],
	[5, new WP(r.moegiiro, r.hanadairo)],
	[6, new WP(r.konniro, r.araishu)],
	[7, new WP(r.urahairo, r.toushoku)],
	[8, new WP(r.taishairo, r.fujiiro)],
	[9, new WP(r.fujinando, r.kyoumurasaki)],
	[10, new WP(r.rokoucha, r.taishairo)],
	[11, new WP(r.nezumiiro, r.shiracha)],
	[12, new WP(r.nandonezumi, r.ochibairo)],
	[13, new WP(r.hiwadairo, r.botannezumi)],
	[14, new WP(r.usukihada, r.koubaiiro)],
	[15, new WP(r.fujiiro, r.aotakeiro)],
	[16, new WP(r.kamenozoki, r.beniebicha)],
	[17, new WP(r.usuhi, r.wakatakeiro)],
	[18, new WP(r.kokushi, r.sakuranezumi)],
	[19, new WP(r.hiwamoegi, r.tabakoiro)],
	[20, new WP(r.benifuji, r.usuasagi)],
	[21, new WP(r.araishu, r.wakatakeiro)],
	[22, new WP(r.gunjouiro, r.kiiro)],
	[23, new WP(r.usumurasaki, r.toumorokoshiiro)],
	[24, new WP(r.botannezumi, r.kenpouiro)],
	[25, new WP(r.suzumecha, r.mizuiro)],
	[26, new WP(r.kobichairo, r.kincha)],
	[27, new WP(r.nikuiro, r.sekibaniro)],
	[28, new WP(r.konniro, r.akanoshirotsurubami)],
	[29, new WP(r.sorairo, r.uguisuiro)],
	[30, new WP(r.nezumiiro, r.benikabairo)],
	[31, new WP(r.usutamagoiro, r.shuiro)],
	[32, new WP(r.hiwamoegi, r.fukiiro)],
	[33, new WP(r.hiwadairo, r.sekibaniro)],
	[34, new WP(r.usukurenai, r.ginnezu)],
	[35, new WP(r.beniiro, r.umenezu)],
	[36, new WP(r.kihadairo, r.byakuroku)],
	[37, new WP(r.ayameiro, r.kakiiro_dark)],
	[38, new WP(r.tokiwairo, r.gunjouiro)],
	[39, new WP(r.enjiiro, r.katsuiro)],
	[40, new WP(r.kakishibuiro, r.nataneiro)],
	[41, new WP(r.rokoucha, r.usuasagi)],
	[42, new WP(r.murasakiiro, r.yamabukicha)],
	[43, new WP(r.hashitairo, r.nikuiro)],
	[44, new WP(r.usuhanada, r.oitakeiro)],
	[45, new WP(r.hadairo, r.kanariyairo)],
	[46, new WP(r.toushoku, r.kuroiro)],
	[47, new WP(r.usuiro, r.suzumecha)],
	[48, new WP(r.botaniro, r.katsuiro)],
	[49, new WP(r.kamenozoki, r.aoiro)],
	[50, new WP(r.kokushi, r.shiracha)],
	[51, new WP(r.aoiro, r.beniiro)],
	[52, new WP(r.kuroiro, r.mushikuriiro)],
	[53, new WP(r.koujiiro, r.kokushi)],
	[54, new WP(r.aotakeiro, r.fukagawanezumi)],
	[55, new WP(r.choushuniro, r.shiroiro)],
	[56, new WP(r.usuiro, r.murasakiiro)],
	[57, new WP(r.kokiiro, r.sekibaniro)],
	[58, new WP(r.wakatakeiro, r.tobiiro)],
	[59, new WP(r.aokuchiba, r.usukurenai)],
	[60, new WP(r.kokihanada, r.usutamagoiro)],
	[61, new WP(r.kakitsubatairo, r.hiwairo)],
	[62, new WP(r.kuroiro, r.kiiro)],
	[63, new WP(r.kurikawairo, r.hanaasagi)],
	[64, new WP(r.hashitairo, r.futaai)],
	[65, new WP(r.kihadairo, r.usuasagi)],
	[66, new WP(r.mirucha, r.aburairo)],
	[67, new WP(r.kokihanada, r.usuhanada)],
	[68, new WP(r.kiiro, r.umenezu)],
	[69, new WP(r.kuroiro, r.haiiro)],
	[70, new WP(r.miruiro, r.hiwadairo)],
	[71, new WP(r.fukiiro, r.benikabairo)],
	[72, new WP(r.kamenozoki, r.mushikuriiro)],
	[73, new WP(r.matsubairo, r.kobichairo)],
	[74, new WP(r.nandonezumi, r.byakuroku)],
	[75, new WP(r.kamenozoki, r.hanairo)],
	[76, new WP(r.usutamagoiro, r.haiiro)],
	[77, new WP(r.usuhi, r.hanadairo)],
	[78, new WP(r.mizuasagi, r.tonokoiro)],
	[79, new WP(r.nandonezumi, r.akanoshirotsurubami)],
	[80, new WP(r.mushikuriiro, r.usumurasaki)],
	[81, new WP(r.kincha, r.haiiro)],
	[82, new WP(r.tobiiro, r.kokushi)],
	[83, new WP(r.hanairo, r.kuwairoshiracha)],
	[84, new WP(r.hadairo, r.tetsuiro)],
	[85, new WP(r.nandoiro, r.kakishibuiro)],
	[86, new WP(r.hiwadairo, r.wakatakeiro)],
	[87, new WP(r.nataneiro, r.nikuiro)],
	[88, new WP(r.aoiro, r.hadairo)],
	[89, new WP(r.koujiiro, r.hanairo)],
	[90, new WP(r.hashitairo, r.usukurenai)],
	[91, new WP(r.kurikawairo, r.ameiro)],
	[92, new WP(r.sangoshuiro, r.aotakeiro)],
	[93, new WP(r.fukagawanezumi, r.aokuchiba)],
	[94, new WP(r.miruai, r.shiracha)],
	[95, new WP(r.tobiiro, r.kachiiro)],
	[96, new WP(r.oriibu, r.yamabukicha)],
	[97, new WP(r.nikuiro, r.suzumecha)],
	[98, new WP(r.akanoshirotsurubami, r.hanairo)],
	[99, new WP(r.usutamagoiro, r.hanaasagi)],
	[100, new WP(r.kimirucha, r.fujinando)],
	[101, new WP(r.gunjouiro, r.ikkonzome)],
	[102, new WP(r.shiracha, r.ameiro)],
	[103, new WP(r.kokushi, r.taishairo)],
	[104, new WP(r.mushikuriiro, r.beniiro)],
	[105, new WP(r.ikkonzome, r.oimidori)],
	[106, new WP(r.kachiiro, r.nandoiro)],
	[107, new WP(r.rikyuucha, r.ukoniro)],
	[108, new WP(r.usukurenai, r.kakiiro_dark)],
	[109, new WP(r.usutamagoiro, r.aimirucha)],
	[110, new WP(r.tobichairo, r.kogechairo)],
	[111, new WP(r.usutamagoiro, r.wakakusairo)],
	[112, new WP(r.kuroiro, r.araishu)],
	[113, new WP(r.hadairo, r.kogechairo)],
	[114, new WP(r.nandoiro, r.yamabukiiro)],
	[115, new WP(r.usukihada, r.anzuiro)],
	[116, new WP(r.kikyoiro, r.ikkonzome)],
	[117, new WP(r.enjiiro, r.kuroiro)],
	[118, new WP(r.kogechairo, r.yamabukicha)],
	[119, new WP(r.kokihanada, r.fukagawanezumi)],
	[120, new WP(r.ikkonzome, r.benikabairo)],
	[121, new WP(r.miruiro, r.fukiiro, r.tobichairo)],
	[122, new WP(r.aotakeiro, r.tamagoiro, r.enjiiro)],
	[123, new WP(r.sangoshuiro, r.kokiiro, r.kanariyairo)],
	[124, new WP(r.kokeiro, r.yamabukicha, r.ebichairo)],
	[125, new WP(r.hanaasagi, r.sakuranezumi, r.hanairo)],
	[126, new WP(r.yamabukicha, r.gunjouiro, r.shiracha)],
	[127, new WP(r.toumorokoshiiro, r.tokusairo, r.futaai)],
	[128, new WP(r.mizuasagi, r.usumurasaki, r.nikuiro)],
	[129, new WP(r.kicha, r.sorairo, r.ukoniro)],
	[130, new WP(r.beniiro, r.murasakiiro, r.hiwadairo)],
	[131, new WP(r.kabairo, r.asagiiro, r.hiwadairo)],
	[132, new WP(r.aokuchiba, r.kincha, r.mushikuriiro)],
	[133, new WP(r.wakatakeiro, r.beniebicha, r.aokuchiba)],
	[134, new WP(r.usukurenai, r.usumurasaki, r.ayameiro)],
	[135, new WP(r.sorairo, r.mushikuriiro, r.moegiiro)],
	[136, new WP(r.ayameiro, r.kurenai, r.kusairo)],
	[137, new WP(r.suzumecha, r.tokusairo, r.toumorokoshiiro)],
	[138, new WP(r.kincha, r.mizuasagi, r.kanariyairo)],
	[139, new WP(r.ginnezu, r.konniro, r.sorairo)],
	[140, new WP(r.kincha, r.sekibaniro, r.nandoiro)],
	[141, new WP(r.toushoku, r.kokihanada, r.wakakusairo)],
	[142, new WP(r.azukiiro, r.sorairo, r.kihadairo)],
	[143, new WP(r.haiiro, r.aoiro, r.hatobamurasaki)],
	[144, new WP(r.toushoku, r.kuroiro, r.botaniro)],
	[145, new WP(r.kachiiro, r.tobichairo, r.nataneiro)],
	[146, new WP(r.kincha, r.tokiwairo, r.namakabeiro)],
	[147, new WP(r.byakuroku, r.beniebicha, r.koubaiiro)],
	[148, new WP(r.yamabukiiro, r.hanaasagi, r.aburairo)],
	[149, new WP(r.tetsuiro, r.toushoku, r.aburairo)],
	[150, new WP(r.hadairo, r.nataneiro, r.urahairo)],
	[151, new WP(r.koujiiro, r.hanadairo, r.mushikuriiro)],
	[152, new WP(r.suzumecha, r.fukagawanezumi, r.tobiiro)],
	[153, new WP(r.usukurenai, r.yamabukiiro, r.nataneiro)],
	[154, new WP(r.enjiiro, r.kiiro, r.aoiro)],
	[155, new WP(r.aotakeiro, r.benikakiiro, r.konniro)],
	[156, new WP(r.murasakiiro, r.aburairo, r.seijiiro)],
	[157, new WP(r.suouiro, r.aburairo, r.usuhanada)],
	[158, new WP(r.taishairo, r.hiwamoegi, r.kanariyairo)],
	[159, new WP(r.usuasagi, r.kicha, r.fujiiro)],
	[160, new WP(r.ainezumi, r.kobichairo, r.kihadairo)],
	[161, new WP(r.tonokoiro, r.katsuiro, r.tobichairo)],
	[162, new WP(r.matsubairo, r.choushuniro, r.hatobamurasaki)],
	[163, new WP(r.byakuroku, r.nandoiro, r.ukoniro)],
	[164, new WP(r.yamabukiiro, r.murasakiiro, r.shuiro)],
	[165, new WP(r.kurikawairo, r.koubaiiro, r.ikkonzome)],
	[166, new WP(r.araishu, r.usukihada, r.tetsuiro)],
	[167, new WP(r.kamenozoki, r.akuiro, r.hanadairo)],
	[168, new WP(r.hanadairo, r.kanariyairo, r.botannezumi)],
	[169, new WP(r.nikuiro, r.haiiro, r.usutamagoiro)],
	[170, new WP(r.botaniro, r.yamabukiiro, r.ayameiro)],
	[171, new WP(r.koujiiro, r.urahairo, r.ebichairo)],
	[172, new WP(r.nandoiro, r.ayameiro, r.taishairo)],
	[173, new WP(r.kanariyairo, r.akanoshirotsurubami, r.byakuroku)],
	[174, new WP(r.kokiiro, r.usuiro, r.nikuiro)],
	[175, new WP(r.kuwairoshiracha, r.tonokoiro, r.kikyoiro)],
	[176, new WP(r.usuasagi, r.tokiiro, r.hadairo)],
	[177, new WP(r.kimirucha, r.ebichairo, r.fujiiro)],
	[178, new WP(r.fukagawanezumi, r.shiracha, r.nandonezumi)],
	[179, new WP(r.shuiro, r.gunjouiro, r.kincha)],
	[180, new WP(r.usumurasaki, r.ginnezu, r.toumorokoshiiro)],
	[181, new WP(r.kakitsubatairo, r.murasakiiro, r.beniiro)],
	[182, new WP(r.kogechairo, r.hiwadairo, r.konniro)],
	[183, new WP(r.botannezumi, r.ayameiro, r.fujinezumi)],
	[184, new WP(r.rikyuucha, r.shiracha, r.koubaiiro)],
	[185, new WP(r.usutamagoiro, r.umenezu, r.suzumecha)],
	[186, new WP(r.tobiiro, r.aoiro, r.fukiiro)],
	[187, new WP(r.usuiro, r.katsuiro, r.hashitairo)],
	[188, new WP(r.seijiiro, r.matsubairo, r.sorairo)],
	[189, new WP(r.mizuasagi, r.kanariyairo, r.sensaicha)],
	[190, new WP(r.kuroiro, r.kabairo, r.shiracha)],
	[191, new WP(r.aoiro, r.umenezu, r.yamabukicha)],
	[192, new WP(r.tamagoiro, r.fujinezumi, r.kogechairo)],
	[193, new WP(r.oitakeiro, r.usukihada, r.araishu)],
	[194, new WP(r.benikakiiro, r.usuhanada, r.hadairo)],
	[195, new WP(r.koubaiiro, r.usutamagoiro, r.ginnezu)],
	[196, new WP(r.nataneiro, r.kikyoiro, r.kamenozoki)],
	[197, new WP(r.futaai, r.usukurenai, r.ginnezu)],
	[198, new WP(r.midoriiro, r.ukoniro, r.kuriume)],
	[199, new WP(r.gunjouiro, r.azukicha, r.uguisucha)],
	[200, new WP(r.kuwairoshiracha, r.beniiro, r.oimidori)],
	[201, new WP(r.oriibu, r.araishu, r.seijiiro)],
	[202, new WP(r.seijiiro, r.sekibaniro, r.byakuroku)],
	[203, new WP(r.kouiro, r.miruiro, r.usutamagoiro)],
	[204, new WP(r.botaniro, r.fukagawanezumi, r.taishairo)],
	[205, new WP(r.kouiro, r.ebichairo, r.murasakiiro)],
	[206, new WP(r.nikuiro, r.taishairo, r.kincha)],
	[207, new WP(r.kuroiro, r.urahairo, r.choujicha)],
	[208, new WP(r.nandonezumi, r.mushikuriiro, r.nandoiro)],
	[209, new WP(r.koujiiro, r.sorairo, r.shiracha)],
	[210, new WP(r.kanariyairo, r.miruiro, r.toumorokoshiiro)],
	[211, new WP(r.konniro, r.kokikuchinashi, r.kokeiro)],
	[212, new WP(r.ginsusutake, r.sorairo, r.benikabairo)],
	[213, new WP(r.ukoniro, r.kamenozoki, r.kouiro)],
	[214, new WP(r.choujicha, r.shiracha, r.murasakiiro)],
	[215, new WP(r.umemurasaki, r.tamagoiro, r.aoiro)],
	[216, new WP(r.benikakiiro, r.kuroiro, r.midoriiro)],
	[217, new WP(r.ebichairo, r.fukiiro, r.tokiwairo)],
	[218, new WP(r.fujinezumi, r.fujiiro, r.katsuiro)],
	[219, new WP(r.benikakiiro, r.miruai, r.oimidori)],
	[220, new WP(r.hashitairo, r.ichigoiro, r.fukiiro)],
	[221, new WP(r.kuroiro, r.beniiro, r.ginnezu)],
	[222, new WP(r.koujiiro, r.yamabukicha, r.ameiro)],
	[223, new WP(r.umenezu, r.fukiiro, r.byakuroku)],
	[224, new WP(r.ainezumi, r.koubaiiro, r.kokiiro)],
	[225, new WP(r.ebiiro, r.miruai, r.enjiiro)],
	[226, new WP(r.murasakiiro, r.tamagoiro, r.kurikawairo)],
	[227, new WP(r.hanaasagi, r.fukagawanezumi, r.tokiiro)],
	[228, new WP(r.beniiro, r.ginnezu, r.usutamagoiro)],
	[229, new WP(r.ginnezu, r.sensaicha, r.kincha)],
	[230, new WP(r.araishu, r.byakuroku, r.seijiiro)],
	[231, new WP(r.tobiiro, r.ikkonzome, r.usuhanada)],
	[232, new WP(r.konniro, r.enjiiro, r.tonokoiro)],
	[233, new WP(r.hanairo, r.beniiro, r.kimirucha)],
	[234, new WP(r.kamenozoki, r.kobichairo, r.toumorokoshiiro)],
	[235, new WP(r.koujiiro, r.shiracha, r.usuiro)],
	[236, new WP(r.usukeshimurasaki, r.gunjouiro, r.kicha)],
	[237, new WP(r.beniiro, r.sorairo, r.akanoshirotsurubami)],
	[238, new WP(r.haiiro, r.kakitsubatairo, r.fukiiro)],
	[239, new WP(r.umenezu, r.urahairo, r.usuaokuchiba)],
	[240, new WP(r.kakiiro_dark, r.hanaasagi, r.kiiro)],
	[241, new WP(r.shuiro, r.ainezumi, r.usutamagoiro, r.ochibairo)],
	[242, new WP(r.usukurenai, r.tokiwairo, r.kuriume, r.kuroiro)],
	[243, new WP(r.hiwadairo, r.mirucha, r.shiracha, r.sekibaniro)],
	[244, new WP(r.umenezu, r.nandoiro, r.kakishibuiro, r.yamabatoiro)],
	[245, new WP(r.kikujin, r.sekibaniro, r.kokihanada, r.beniiro)],
	[246, new WP(r.kakiiro_dark, r.nikuiro, r.mushikuriiro, r.toumorokoshiiro)],
	[247, new WP(r.hiwadairo, r.aotakeiro, r.gunjouiro, r.ukoniro)],
	[248, new WP(r.fujiiro, r.kicha, r.usukurenai, r.ebiiro)],
	[249, new WP(r.aburairo, r.ainezumi, r.tobiiro, r.akuiro)],
	[250, new WP(r.usuaokuchiba, r.anzuiro, r.wakatakeiro, r.mizuiro)],
	[251, new WP(r.akaneiro, r.tokiwairo, r.sekibaniro, r.kiiro)],
	[252, new WP(r.usuhi, r.kihadairo, r.nandonezumi, r.hiwadairo)],
	[
		253,
		new WP(r.kokikuchinashi, r.kanariyairo, r.kakitsubatairo, r.sekibaniro),
	],
	[254, new WP(r.benifuji, r.oriibu, r.mushikuriiro, r.nikuiro)],
	[255, new WP(r.usuasagi, r.kuroiro, r.usuaokuchiba, r.hiwadairo)],
	[256, new WP(r.kuroiro, r.toushoku, r.kouiro, r.kusairo)],
	[257, new WP(r.aoiro, r.akairo, r.hashitairo, r.yamabukiiro)],
	[258, new WP(r.tonokoiro, r.oriibu, r.ebichairo, r.nandoiro)],
	[259, new WP(r.nandonezumi, r.haiiro, r.kanariyairo, r.katsuiro)],
	[260, new WP(r.choushuniro, r.wakatakeiro, r.urahairo, r.kouiro)],
	[261, new WP(r.haiiro, r.akaneiro, r.usutamagoiro, r.usuasagi)],
	[262, new WP(r.shiracha, r.usuhi, r.moegiiro, r.aokuchiba)],
	[263, new WP(r.tonokoiro, r.sekibaniro, r.kuriume, r.byakuroku)],
	[264, new WP(r.nikuiro, r.hanaasagi, r.shuiro, r.wakanaeiro)],
	[265, new WP(r.kokeiro, r.choushuniro, r.kachiiro, r.ukoniro)],
	[266, new WP(r.akairo, r.shiracha, r.matsubairo, r.aotakeiro)],
	[267, new WP(r.aoiro, r.koujiiro, r.aotakeiro, r.tamagoiro)],
	[268, new WP(r.sensaicha, r.umenezu, r.mizuiro, r.hiwadairo)],
	[269, new WP(r.hashitairo, r.ebichairo, r.hiwadairo, r.kuroiro)],
	[270, new WP(r.mushikuriiro, r.usuhi, r.mirucha, r.moegiiro)],
	[271, new WP(r.seijiiro, r.tetsuiro, r.ichigoiro, r.nandonezumi)],
	[272, new WP(r.sorairo, r.byakuroku, r.toushoku, r.usutamagoiro)],
	[273, new WP(r.suouiro, r.ginnezu, r.tokiiro, r.choujicha)],
	[274, new WP(r.rokoucha, r.usumurasaki, r.anzuiro, r.usuhanada)],
	[275, new WP(r.suzumecha, r.akuiro, r.akanoshirotsurubami, r.kokiiro)],
	[276, new WP(r.hadairo, r.kuroiro, r.usukurenai, r.wakakusairo)],
	[277, new WP(r.koubaiiro, r.kachiiro, r.oriibu, r.botaniro)],
	[278, new WP(r.aburairo, r.miruai, r.moegiiro, r.tamagoiro)],
	[279, new WP(r.hiwadairo, r.kokihanada, r.kouiro, r.akuiro)],
	[280, new WP(r.miruiro, r.kokiiro, r.usuhi, r.benifuji)],
	[281, new WP(r.nandoiro, r.aotakeiro, r.usutamagoiro, r.seijiiro)],
	[282, new WP(r.hatobamurasaki, r.mikiiro, r.seijiiro, r.usuhi)],
	[283, new WP(r.ebichairo, r.oimidori, r.mizuasagi, r.azukicha)],
	[284, new WP(r.hizameiro, r.wakatakeiro, r.ukoniro, r.miruai)],
	[285, new WP(r.umenezu, r.anzuiro, r.kuriume, r.byakuroku)],
	[286, new WP(r.yamabukiiro, r.asagiiro, r.kuriume, r.hanairo)],
	[287, new WP(r.kamenozoki, r.usukurenai, r.usuaokuchiba, r.usuasagi)],
	[288, new WP(r.koujiiro, r.kokiiro, r.kenpouiro, r.kuroiro)],
	[289, new WP(r.kachiiro, r.kanariyairo, r.hanairo, r.hiwairo)],
	[290, new WP(r.miruiro, r.kurikawairo, r.usutamagoiro, r.seijiiro)],
	[291, new WP(r.usuasagi, r.seijiiro, r.wakatakeiro, r.hiwairo)],
	[292, new WP(r.usutamagoiro, r.akuiro, r.tonokoiro, r.ochibairo)],
	[293, new WP(r.hiwadairo, r.byakuroku, r.chigusanezumi, r.midoriiro)],
	[294, new WP(r.moegiiro, r.tamagoiro, r.sorairo, r.mushikuriiro)],
	[295, new WP(r.tamagoiro, r.kiiro, r.kachiiro, r.aoiro)],
	[296, new WP(r.kobichairo, r.fukiiro, r.mushikuriiro, r.sekibaniro)],
	[297, new WP(r.kuriume, r.koujiiro, r.hanairo, r.mirucha)],
	[298, new WP(r.kanariyairo, r.anzuiro, r.hiwadairo, r.kuroiro)],
	[299, new WP(r.kikujin, r.kouiro, r.nandoiro, r.ususuo)],
	[300, new WP(r.usuasagi, r.tamagoiro, r.araishu, r.byakuroku)],
	[301, new WP(r.akairo, r.shiracha, r.hashitairo, r.matsubairo)],
	[302, new WP(r.tamagoiro, r.akuiro, r.nandoiro, r.mizuiro)],
	[303, new WP(r.usukihada, r.anzuiro, r.ginnezu, r.sensaicha)],
	[304, new WP(r.aotakeiro, r.tamagoiro, r.rokoucha, r.tobiiro)],
	[305, new WP(r.tonokoiro, r.ukoniro, r.byakuroku, r.nataneiro)],
	[306, new WP(r.kusairo, r.mizuiro, r.aotakeiro, r.kanariyairo)],
	[307, new WP(r.kakitsubatairo, r.fujiiro, r.enjiiro, r.hashitairo)],
	[308, new WP(r.kabairo, r.sakuranezumi, r.seijiiro, r.kurenai)],
	[309, new WP(r.kincha, r.kokikuchinashi, r.hanadairo, r.hanairo)],
	[310, new WP(r.oriibu, r.tonokoiro, r.sensaicha, r.mushikuriiro)],
	[311, new WP(r.benikabairo, r.wakanaeiro, r.tamagoiro, r.hiwairo)],
	[312, new WP(r.kuriume, r.chigusanezumi, r.katsuiro, r.koujiiro)],
	[313, new WP(r.enjiiro, r.kuroiro, r.tokiwairo, r.kiiro)],
	[314, new WP(r.kokushi, r.gunjouiro, r.usukurenai, r.tobiiro)],
	[315, new WP(r.kincha, r.umemurasaki, r.mushikuriiro, r.araishu)],
	[316, new WP(r.ayameiro, r.beniebicha, r.kusairo, r.murasakiiro)],
	[317, new WP(r.byakuroku, r.usukouiro, r.kanariyairo, r.akuiro)],
	[318, new WP(r.uguisucha, r.tetsuiro, r.miruai, r.aimirucha)],
	[319, new WP(r.ukoniro, r.koujiiro, r.hiwadairo, r.moegiiro)],
	[320, new WP(r.kikujin, r.sangoshuiro, r.fukagawanezumi, r.mushikuriiro)],
	[321, new WP(r.mushikuriiro, r.sorairo, r.umenezu, r.sensaicha)],
	[322, new WP(r.kikyoiro, r.umemurasaki, r.kakiiro_dark, r.akairo)],
	[
		323,
		new WP(r.toumorokoshiiro, r.nataneiro, r.kuroiro, r.akanoshirotsurubami),
	],
	[324, new WP(r.benikabairo, r.hashitairo, r.usuhanada, r.ginnezu)],
	[325, new WP(r.tetsuiro, r.usukihada, r.usuhi, r.yamabukicha)],
	[326, new WP(r.hiwamoegi, r.mushikuriiro, r.anzuiro, r.wakakusairo)],
	[327, new WP(r.akuiro, r.usukurenai, r.usuiro, r.hiwadairo)],
	[328, new WP(r.kakiiro_dark, r.oitakeiro, r.kokikuchinashi, r.kogechairo)],
	[329, new WP(r.sekibaniro, r.tamagoiro, r.usuiro, r.kakitsubatairo)],
	[330, new WP(r.mizuiro, r.sorairo, r.kuwairoshiracha, r.nandonezumi)],
	[331, new WP(r.usumurasaki, r.murasakiiro, r.ususuo, r.kachiiro)],
	[332, new WP(r.sensaicha, r.miruai, r.sangoshuiro, r.kurenai)],
	[333, new WP(r.seijiiro, r.kanariyairo, r.kuriume, r.aoiro)],
	[334, new WP(r.oriibu, r.nandoiro, r.wakakusairo, r.hadairo)],
	[335, new WP(r.beniebicha, r.sekibaniro, r.koujiiro, r.murasakiiro)],
	[336, new WP(r.tobiiro, r.usukurenai, r.usutamagoiro, r.aimirucha)],
	[337, new WP(r.kurikawairo, r.kuwazomeiro, r.kuroiro, r.benifuji)],
	[338, new WP(r.yamabukiiro, r.usuiro, r.miruai, r.beniiro)],
	[339, new WP(r.kabairo, r.fukiiro, r.hanairo, r.fukagawanezumi)],
	[340, new WP(r.anzuiro, r.wakatakeiro, r.kuroiro, r.ginnezu)],
	[341, new WP(r.moegiiro, r.fukagawanezumi, r.sensaicha, r.araishu)],
	[342, new WP(r.sensaicha, r.tamagoiro, r.nikuiro, r.ginsusutake)],
	[343, new WP(r.shiracha, r.namakabeiro, r.hanadairo, r.kuriume)],
	[344, new WP(r.hashitairo, r.toumorokoshiiro, r.kuroiro, r.gunjouiro)],
	[345, new WP(r.kikyoiro, r.tobiiro, r.mizuiro, r.mizuasagi)],
	[346, new WP(r.hiwairo, r.botaniro, r.yamabatoiro, r.byakuroku)],
	[347, new WP(r.wakatakeiro, r.katsuiro, r.hatobamurasaki, r.kokeiro)],
	[348, new WP(r.kakitsubatairo, r.moegiiro, r.sensaicha, r.kuwairoshiracha)],
];
